### ISSUE TITLE
Python3 code not working!!!!!

### ISSUE THREAD

**Issue by SnehaBheemireddy** [ebi-uniprot/uniprot-manual#19]
~\anaconda3\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by dlrice** [comment]
Hi, thank you for reporting this issue. Do you mind please providing the script and some context that causes this 404 error to arise?

**Comment by SnehaBheemireddy** [comment]
Hello. Thank you for such a quick reply. I have tried the python3 code of the id mapping given in the manual which caused the above error!

**Comment by SnehaBheemireddy** [comment]
Not only that, any request made to uniprot, or ebi has the same error!!!!!!!  [[[HTTPError: 400 Client Error: Bad Request for url: [https://rest.uniprot.org/](https://rest.uniprot.org//uniprotkb/search?query**)

**Comment by aurel-l** [comment]
Can't reproduce
